// flow-typed signature: ccc9f8c1ff18089b01f65cdf3fcc70cf
// flow-typed version: <<STUB>>/babel-plugin-espower_v^2.3.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-espower'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-espower' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-espower/create' {
  declare module.exports: any;
}

declare module 'babel-plugin-espower/lib/babel-assertion-visitor' {
  declare module.exports: any;
}

declare module 'babel-plugin-espower/lib/babel-espower-visitor' {
  declare module.exports: any;
}

declare module 'babel-plugin-espower/lib/create-espower-visitor' {
  declare module.exports: any;
}

declare module 'babel-plugin-espower/lib/default-options' {
  declare module.exports: any;
}

declare module 'babel-plugin-espower/lib/define-properties' {
  declare module.exports: any;
}

declare module 'babel-plugin-espower/lib/power-assert-recorder' {
  declare module.exports: any;
}

declare module 'babel-plugin-espower/lib/to-be-captured' {
  declare module.exports: any;
}

declare module 'babel-plugin-espower/lib/to-be-skipped' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-espower/create.js' {
  declare module.exports: $Exports<'babel-plugin-espower/create'>;
}
declare module 'babel-plugin-espower/index' {
  declare module.exports: $Exports<'babel-plugin-espower'>;
}
declare module 'babel-plugin-espower/index.js' {
  declare module.exports: $Exports<'babel-plugin-espower'>;
}
declare module 'babel-plugin-espower/lib/babel-assertion-visitor.js' {
  declare module.exports: $Exports<'babel-plugin-espower/lib/babel-assertion-visitor'>;
}
declare module 'babel-plugin-espower/lib/babel-espower-visitor.js' {
  declare module.exports: $Exports<'babel-plugin-espower/lib/babel-espower-visitor'>;
}
declare module 'babel-plugin-espower/lib/create-espower-visitor.js' {
  declare module.exports: $Exports<'babel-plugin-espower/lib/create-espower-visitor'>;
}
declare module 'babel-plugin-espower/lib/default-options.js' {
  declare module.exports: $Exports<'babel-plugin-espower/lib/default-options'>;
}
declare module 'babel-plugin-espower/lib/define-properties.js' {
  declare module.exports: $Exports<'babel-plugin-espower/lib/define-properties'>;
}
declare module 'babel-plugin-espower/lib/power-assert-recorder.js' {
  declare module.exports: $Exports<'babel-plugin-espower/lib/power-assert-recorder'>;
}
declare module 'babel-plugin-espower/lib/to-be-captured.js' {
  declare module.exports: $Exports<'babel-plugin-espower/lib/to-be-captured'>;
}
declare module 'babel-plugin-espower/lib/to-be-skipped.js' {
  declare module.exports: $Exports<'babel-plugin-espower/lib/to-be-skipped'>;
}
