// flow-typed signature: e34fd8be7f388ea023c14c8530b01f70
// flow-typed version: <<STUB>>/worker-loader_v^0.8.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'worker-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'worker-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'worker-loader/createInlineWorker' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/inline-fallbacks/entry' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/inline-fallbacks/w1' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/inline-fallbacks/w2' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/inline-options/entry' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/inline-options/w1' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/inline-options/w2' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/inline-query/entry' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/inline-query/worker' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/name-options/entry' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/name-options/w1' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/name-options/w2' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/name-query/entry' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/name-query/worker' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/no-fallbacks/entry' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/no-fallbacks/w1' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/no-fallbacks/w2' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/worker/entry' {
  declare module.exports: any;
}

declare module 'worker-loader/test/fixtures/worker/worker' {
  declare module.exports: any;
}

declare module 'worker-loader/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'worker-loader/createInlineWorker.js' {
  declare module.exports: $Exports<'worker-loader/createInlineWorker'>;
}
declare module 'worker-loader/index' {
  declare module.exports: $Exports<'worker-loader'>;
}
declare module 'worker-loader/index.js' {
  declare module.exports: $Exports<'worker-loader'>;
}
declare module 'worker-loader/test/fixtures/inline-fallbacks/entry.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/inline-fallbacks/entry'>;
}
declare module 'worker-loader/test/fixtures/inline-fallbacks/w1.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/inline-fallbacks/w1'>;
}
declare module 'worker-loader/test/fixtures/inline-fallbacks/w2.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/inline-fallbacks/w2'>;
}
declare module 'worker-loader/test/fixtures/inline-options/entry.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/inline-options/entry'>;
}
declare module 'worker-loader/test/fixtures/inline-options/w1.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/inline-options/w1'>;
}
declare module 'worker-loader/test/fixtures/inline-options/w2.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/inline-options/w2'>;
}
declare module 'worker-loader/test/fixtures/inline-query/entry.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/inline-query/entry'>;
}
declare module 'worker-loader/test/fixtures/inline-query/worker.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/inline-query/worker'>;
}
declare module 'worker-loader/test/fixtures/name-options/entry.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/name-options/entry'>;
}
declare module 'worker-loader/test/fixtures/name-options/w1.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/name-options/w1'>;
}
declare module 'worker-loader/test/fixtures/name-options/w2.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/name-options/w2'>;
}
declare module 'worker-loader/test/fixtures/name-query/entry.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/name-query/entry'>;
}
declare module 'worker-loader/test/fixtures/name-query/worker.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/name-query/worker'>;
}
declare module 'worker-loader/test/fixtures/no-fallbacks/entry.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/no-fallbacks/entry'>;
}
declare module 'worker-loader/test/fixtures/no-fallbacks/w1.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/no-fallbacks/w1'>;
}
declare module 'worker-loader/test/fixtures/no-fallbacks/w2.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/no-fallbacks/w2'>;
}
declare module 'worker-loader/test/fixtures/worker/entry.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/worker/entry'>;
}
declare module 'worker-loader/test/fixtures/worker/worker.js' {
  declare module.exports: $Exports<'worker-loader/test/fixtures/worker/worker'>;
}
declare module 'worker-loader/test/index.js' {
  declare module.exports: $Exports<'worker-loader/test/index'>;
}
